repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        types: [python]
        entry: poetry run mypy --strict

      - id: pytest
        name: pytest
        language: system
        pass_filenames: false
        always_run: true
        entry: poetry run pytest

  - repo: https://github.com/psf/black
    rev: "23.11.0"
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
